<?php

namespace app\controllers;
use Yii;
use app\utils\D;

class MainController extends \yii\web\Controller
{
    public function beforeAction($action)
    {

        if (Yii::$app->user->isGuest)
        {
          //  D::echor("ПОЛЬЗОВАТЕЬ НЕ АВТОРИЗОВАН");
            Yii::$app->user->logout();
           if (Yii::$app->controller->action->id != 'login') $this->redirect(['site/login']);
        }
         //
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}
